const getCountries = async (req, res, next) => {
  try {
    res.status(200).send({
      paises: [
        { "c\u00f3digo": "ABW", pais: "Aruba" },
        { "c\u00f3digo": "AFG", pais: "Afganist\u00c3\u00a1n" },
        { "c\u00f3digo": "AGO", pais: "Angola" },
        { "c\u00f3digo": "AIA", pais: "Anguila" },
        { "c\u00f3digo": "ALA", pais: "Islas \u00c3\u0085land" },
        { "c\u00f3digo": "ALB", pais: "Albania" },
        { "c\u00f3digo": "AND", pais: "Andorra" },
        {
          "c\u00f3digo": "ARE",
          pais: "Emiratos \u00c3\u0081rabes Unidos (Los)",
        },
        { "c\u00f3digo": "ARG", pais: "Argentina" },
        { "c\u00f3digo": "ARM", pais: "Armenia" },
        { "c\u00f3digo": "ASM", pais: "Samoa Americana" },
        { "c\u00f3digo": "ATA", pais: "Ant\u00c3\u00a1rtida" },
        {
          "c\u00f3digo": "ATF",
          pais: "Territorios Australes Franceses (los)",
        },
        { "c\u00f3digo": "ATG", pais: "Antigua y Barbuda" },
        { "c\u00f3digo": "AUS", pais: "Australia" },
        { "c\u00f3digo": "AUT", pais: "Austria" },
        { "c\u00f3digo": "AZE", pais: "Azerbaiy\u00c3\u00a1n" },
        { "c\u00f3digo": "BDI", pais: "Burundi" },
        { "c\u00f3digo": "BEL", pais: "B\u00c3\u00a9lgica" },
        { "c\u00f3digo": "BEN", pais: "Ben\u00c3\u00adn" },
        { "c\u00f3digo": "BES", pais: "Bonaire, San Eustaquio y Saba" },
        { "c\u00f3digo": "BFA", pais: "Burkina Faso" },
        { "c\u00f3digo": "BGD", pais: "Banglad\u00c3\u00a9s" },
        { "c\u00f3digo": "BGR", pais: "Bulgaria" },
        { "c\u00f3digo": "BHR", pais: "Bar\u00c3\u00a9in" },
        { "c\u00f3digo": "BHS", pais: "Bahamas (las)" },
        { "c\u00f3digo": "BIH", pais: "Bosnia y Herzegovina" },
        { "c\u00f3digo": "BLM", pais: "San Bartolom\u00c3\u00a9" },
        { "c\u00f3digo": "BLR", pais: "Bielorrusia" },
        { "c\u00f3digo": "BLZ", pais: "Belice" },
        { "c\u00f3digo": "BMU", pais: "Bermudas" },
        { "c\u00f3digo": "BOL", pais: "Bolivia, Estado Plurinacional de" },
        { "c\u00f3digo": "BRA", pais: "Brasil" },
        { "c\u00f3digo": "BRB", pais: "Barbados" },
        { "c\u00f3digo": "BRN", pais: "Brun\u00c3\u00a9i Darussalam" },
        { "c\u00f3digo": "BTN", pais: "But\u00c3\u00a1n" },
        { "c\u00f3digo": "BVT", pais: "Isla Bouvet" },
        { "c\u00f3digo": "BWA", pais: "Botsuana" },
        {
          "c\u00f3digo": "CAF",
          pais: "Rep\u00c3\u00bablica Centroafricana (la)",
        },
        { "c\u00f3digo": "CAN", pais: "Canad\u00c3\u00a1" },
        { "c\u00f3digo": "CCK", pais: "Islas Cocos (Keeling)" },
        { "c\u00f3digo": "CHE", pais: "Suiza" },
        { "c\u00f3digo": "CHL", pais: "Chile" },
        { "c\u00f3digo": "CHN", pais: "China" },
        { "c\u00f3digo": "CIV", pais: "C\u00c3\u00b4te d'Ivoire" },
        { "c\u00f3digo": "CMR", pais: "Camer\u00c3\u00ban" },
        {
          "c\u00f3digo": "COD",
          pais: "Congo (la Rep\u00c3\u00bablica Democr\u00c3\u00a1tica del)",
        },
        { "c\u00f3digo": "COG", pais: "Congo" },
        { "c\u00f3digo": "COK", pais: "Islas Cook (las)" },
        { "c\u00f3digo": "COL", pais: "Colombia" },
        { "c\u00f3digo": "COM", pais: "Comoras" },
        { "c\u00f3digo": "CPV", pais: "Cabo Verde" },
        { "c\u00f3digo": "CRI", pais: "Costa Rica" },
        { "c\u00f3digo": "CUB", pais: "Cuba" },
        { "c\u00f3digo": "CUW", pais: "Cura\u00c3\u00a7ao" },
        { "c\u00f3digo": "CXR", pais: "Isla de Navidad" },
        { "c\u00f3digo": "CYM", pais: "Islas Caim\u00c3\u00a1n (las)" },
        { "c\u00f3digo": "CYP", pais: "Chipre" },
        { "c\u00f3digo": "CZE", pais: "Rep\u00c3\u00bablica Checa (la)" },
        { "c\u00f3digo": "DEU", pais: "Alemania" },
        { "c\u00f3digo": "DJI", pais: "Yibuti" },
        { "c\u00f3digo": "DMA", pais: "Dominica" },
        { "c\u00f3digo": "DNK", pais: "Dinamarca" },
        {
          "c\u00f3digo": "DOM",
          pais: "Rep\u00c3\u00bablica Dominicana (la)",
        },
        { "c\u00f3digo": "DZA", pais: "Argelia" },
        { "c\u00f3digo": "ECU", pais: "Ecuador" },
        { "c\u00f3digo": "EGY", pais: "Egipto" },
        { "c\u00f3digo": "ERI", pais: "Eritrea" },
        { "c\u00f3digo": "ESH", pais: "Sahara Occidental" },
        { "c\u00f3digo": "ESP", pais: "Espa\u00c3\u00b1a" },
        { "c\u00f3digo": "EST", pais: "Estonia" },
        { "c\u00f3digo": "ETH", pais: "Etiop\u00c3\u00ada" },
        { "c\u00f3digo": "FIN", pais: "Finlandia" },
        { "c\u00f3digo": "FJI", pais: "Fiyi" },
        { "c\u00f3digo": "FLK", pais: "Islas Malvinas [Falkland] (las)" },
        { "c\u00f3digo": "FRA", pais: "Francia" },
        { "c\u00f3digo": "FRO", pais: "Islas Feroe (las)" },
        {
          "c\u00f3digo": "FSM",
          pais: "Micronesia (los Estados Federados de)",
        },
        { "c\u00f3digo": "GAB", pais: "Gab\u00c3\u00b3n" },
        { "c\u00f3digo": "GBR", pais: "Reino Unido (el)" },
        { "c\u00f3digo": "GEO", pais: "Georgia" },
        { "c\u00f3digo": "GGY", pais: "Guernsey" },
        { "c\u00f3digo": "GHA", pais: "Ghana" },
        { "c\u00f3digo": "GIB", pais: "Gibraltar" },
        { "c\u00f3digo": "GIN", pais: "Guinea" },
        { "c\u00f3digo": "GLP", pais: "Guadalupe" },
        { "c\u00f3digo": "GMB", pais: "Gambia (La)" },
        { "c\u00f3digo": "GNB", pais: "Guinea-Bis\u00c3\u00a1u" },
        { "c\u00f3digo": "GNQ", pais: "Guinea Ecuatorial" },
        { "c\u00f3digo": "GRC", pais: "Grecia" },
        { "c\u00f3digo": "GRD", pais: "Granada" },
        { "c\u00f3digo": "GRL", pais: "Groenlandia" },
        { "c\u00f3digo": "GTM", pais: "Guatemala" },
        { "c\u00f3digo": "GUF", pais: "Guayana Francesa" },
        { "c\u00f3digo": "GUM", pais: "Guam" },
        { "c\u00f3digo": "GUY", pais: "Guyana" },
        { "c\u00f3digo": "HKG", pais: "Hong Kong" },
        { "c\u00f3digo": "HMD", pais: "Isla Heard e Islas McDonald" },
        { "c\u00f3digo": "HND", pais: "Honduras" },
        { "c\u00f3digo": "HRV", pais: "Croacia" },
        { "c\u00f3digo": "HTI", pais: "Hait\u00c3\u00ad" },
        { "c\u00f3digo": "HUN", pais: "Hungr\u00c3\u00ada" },
        { "c\u00f3digo": "IDN", pais: "Indonesia" },
        { "c\u00f3digo": "IMN", pais: "Isla de Man" },
        { "c\u00f3digo": "IND", pais: "India" },
        {
          "c\u00f3digo": "IOT",
          pais: "Territorio Brit\u00c3\u00a1nico del Oc\u00c3\u00a9ano \u00c3\u008dndico (el)",
        },
        { "c\u00f3digo": "IRL", pais: "Irlanda" },
        {
          "c\u00f3digo": "IRN",
          pais: "Ir\u00c3\u00a1n (la Rep\u00c3\u00bablica Isl\u00c3\u00a1mica de)",
        },
        { "c\u00f3digo": "IRQ", pais: "Irak" },
        { "c\u00f3digo": "ISL", pais: "Islandia" },
        { "c\u00f3digo": "ISR", pais: "Israel" },
        { "c\u00f3digo": "ITA", pais: "Italia" },
        { "c\u00f3digo": "JAM", pais: "Jamaica" },
        { "c\u00f3digo": "JEY", pais: "Jersey" },
        { "c\u00f3digo": "JOR", pais: "Jordania" },
        { "c\u00f3digo": "JPN", pais: "Jap\u00c3\u00b3n" },
        { "c\u00f3digo": "KAZ", pais: "Kazajist\u00c3\u00a1n" },
        { "c\u00f3digo": "KEN", pais: "Kenia" },
        { "c\u00f3digo": "KGZ", pais: "Kirguist\u00c3\u00a1n" },
        { "c\u00f3digo": "KHM", pais: "Camboya" },
        { "c\u00f3digo": "KIR", pais: "Kiribati" },
        { "c\u00f3digo": "KNA", pais: "San Crist\u00c3\u00b3bal y Nieves" },
        {
          "c\u00f3digo": "KOR",
          pais: "Corea (la Rep\u00c3\u00bablica de)",
        },
        { "c\u00f3digo": "KWT", pais: "Kuwait" },
        {
          "c\u00f3digo": "LAO",
          pais: "Lao, (la) Rep\u00c3\u00bablica Democr\u00c3\u00a1tica Popular",
        },
        { "c\u00f3digo": "LBN", pais: "L\u00c3\u00adbano" },
        { "c\u00f3digo": "LBR", pais: "Liberia" },
        { "c\u00f3digo": "LBY", pais: "Libia" },
        { "c\u00f3digo": "LCA", pais: "Santa Luc\u00c3\u00ada" },
        { "c\u00f3digo": "LIE", pais: "Liechtenstein" },
        { "c\u00f3digo": "LKA", pais: "Sri Lanka" },
        { "c\u00f3digo": "LSO", pais: "Lesoto" },
        { "c\u00f3digo": "LTU", pais: "Lituania" },
        { "c\u00f3digo": "LUX", pais: "Luxemburgo" },
        { "c\u00f3digo": "LVA", pais: "Letonia" },
        { "c\u00f3digo": "MAC", pais: "Macao" },
        {
          "c\u00f3digo": "MAF",
          pais: "San Mart\u00c3\u00adn (parte francesa)",
        },
        { "c\u00f3digo": "MAR", pais: "Marruecos" },
        { "c\u00f3digo": "MCO", pais: "M\u00c3\u00b3naco" },
        { "c\u00f3digo": "MDA", pais: "Moldavia (la Rep" },
        { "c\u00f3digo": "MDG", pais: "Madagascar" },
        { "c\u00f3digo": "MDV", pais: "Maldivas" },
        { "c\u00f3digo": "MEX", pais: "M\u00c3\u00a9xico" },
        { "c\u00f3digo": "MHL", pais: "Islas Marshall (las)" },
        {
          "c\u00f3digo": "MKD",
          pais: "Macedonia (la antigua Rep\u00c3\u00bablica Yugoslava de)",
        },
        { "c\u00f3digo": "MLI", pais: "Mal\u00c3\u00ad" },
        { "c\u00f3digo": "MLT", pais: "Malta" },
        { "c\u00f3digo": "MMR", pais: "Myanmar" },
        { "c\u00f3digo": "MNE", pais: "Montenegro" },
        { "c\u00f3digo": "MNG", pais: "Mongolia" },
        { "c\u00f3digo": "MNP", pais: "Islas Marianas del Norte (las)" },
        { "c\u00f3digo": "MOZ", pais: "Mozambique" },
        { "c\u00f3digo": "MRT", pais: "Mauritania" },
        { "c\u00f3digo": "MSR", pais: "Montserrat" },
        { "c\u00f3digo": "MTQ", pais: "Martinica" },
        { "c\u00f3digo": "MUS", pais: "Mauricio" },
        { "c\u00f3digo": "MWI", pais: "Malaui" },
        { "c\u00f3digo": "MYS", pais: "Malasia" },
        { "c\u00f3digo": "MYT", pais: "Mayotte" },
        { "c\u00f3digo": "NAM", pais: "Namibia" },
        { "c\u00f3digo": "NCL", pais: "Nueva Caledonia" },
        { "c\u00f3digo": "NER", pais: "N\u00c3\u00adger (el)" },
        { "c\u00f3digo": "NFK", pais: "Isla Norfolk" },
        { "c\u00f3digo": "NGA", pais: "Nigeria" },
        { "c\u00f3digo": "NIC", pais: "Nicaragua" },
        { "c\u00f3digo": "NIU", pais: "Niue" },
        { "c\u00f3digo": "NLD", pais: "Pa\u00c3\u00adses Bajos (los)" },
        { "c\u00f3digo": "NOR", pais: "Noruega" },
        { "c\u00f3digo": "NPL", pais: "Nepal" },
        { "c\u00f3digo": "NRU", pais: "Nauru" },
        { "c\u00f3digo": "NZL", pais: "Nueva Zelanda" },
        { "c\u00f3digo": "OMN", pais: "Om\u00c3\u00a1n" },
        { "c\u00f3digo": "PAK", pais: "Pakist\u00c3\u00a1n" },
        { "c\u00f3digo": "PAN", pais: "Panam\u00c3\u00a1" },
        { "c\u00f3digo": "PCN", pais: "Pitcairn" },
        { "c\u00f3digo": "PER", pais: "Per\u00c3\u00ba" },
        { "c\u00f3digo": "PHL", pais: "Filipinas (las)" },
        { "c\u00f3digo": "PLW", pais: "Palaos" },
        { "c\u00f3digo": "PNG", pais: "Pap\u00c3\u00baa Nueva Guinea" },
        { "c\u00f3digo": "POL", pais: "Polonia" },
        { "c\u00f3digo": "PRI", pais: "Puerto Rico" },
        {
          "c\u00f3digo": "PRK",
          pais: "Corea (la Rep\u00c3\u00bablica Democr\u00c3\u00a1tica Popular de)",
        },
        { "c\u00f3digo": "PRT", pais: "Portugal" },
        { "c\u00f3digo": "PRY", pais: "Paraguay" },
        { "c\u00f3digo": "PSE", pais: "Palestina, Estado de" },
        { "c\u00f3digo": "PYF", pais: "Polinesia Francesa" },
        { "c\u00f3digo": "QAT", pais: "Catar" },
        { "c\u00f3digo": "REU", pais: "Reuni\u00c3\u00b3n" },
        { "c\u00f3digo": "ROU", pais: "Rumania" },
        {
          "c\u00f3digo": "RUS",
          pais: "Rusia, (la) Federaci\u00c3\u00b3n de",
        },
        { "c\u00f3digo": "RWA", pais: "Ruanda" },
        { "c\u00f3digo": "SAU", pais: "Arabia Saudita" },
        { "c\u00f3digo": "SDN", pais: "Sud\u00c3\u00a1n (el)" },
        { "c\u00f3digo": "SEN", pais: "Senegal" },
        { "c\u00f3digo": "SGP", pais: "Singapur" },
        {
          "c\u00f3digo": "SGS",
          pais: "Georgia del sur y las islas sandwich del sur",
        },
        {
          "c\u00f3digo": "SHN",
          pais: "Santa Helena, Ascensi\u00c3\u00b3n y Trist\u00c3\u00a1n de Acu\u00c3\u00b1a",
        },
        { "c\u00f3digo": "SJM", pais: "Svalbard y Jan Mayen" },
        { "c\u00f3digo": "SLB", pais: "Islas Salom\u00c3\u00b3n (las)" },
        { "c\u00f3digo": "SLE", pais: "Sierra leona" },
        { "c\u00f3digo": "SLV", pais: "El Salvador" },
        { "c\u00f3digo": "SMR", pais: "San Marino" },
        { "c\u00f3digo": "SOM", pais: "Somalia" },
        { "c\u00f3digo": "SPM", pais: "San Pedro y Miquel\u00c3\u00b3n" },
        { "c\u00f3digo": "SRB", pais: "Serbia" },
        { "c\u00f3digo": "SSD", pais: "Sud\u00c3\u00a1n del Sur" },
        {
          "c\u00f3digo": "STP",
          pais: "Santo Tom\u00c3\u00a9 y Pr\u00c3\u00adncipe",
        },
        { "c\u00f3digo": "SUR", pais: "Surinam" },
        { "c\u00f3digo": "SVK", pais: "Eslovaquia" },
        { "c\u00f3digo": "SVN", pais: "Eslovenia" },
        { "c\u00f3digo": "SWE", pais: "Suecia" },
        { "c\u00f3digo": "SWZ", pais: "Suazilandia" },
        { "c\u00f3digo": "SXM", pais: "Sint Maarten (parte holandesa)" },
        { "c\u00f3digo": "SYC", pais: "Seychelles" },
        {
          "c\u00f3digo": "SYR",
          pais: "Siria, (la) Rep\u00c3\u00bablica \u00c3\u0081rabe",
        },
        { "c\u00f3digo": "TCA", pais: "Islas Turcas y Caicos (las)" },
        { "c\u00f3digo": "TCD", pais: "Chad" },
        { "c\u00f3digo": "TGO", pais: "Togo" },
        { "c\u00f3digo": "THA", pais: "Tailandia" },
        { "c\u00f3digo": "TJK", pais: "Tayikist" },
        { "c\u00f3digo": "TKL", pais: "Tokelau" },
        { "c\u00f3digo": "TKM", pais: "Turkmenist\u00c3\u00a1n" },
        { "c\u00f3digo": "TLS", pais: "Timor-Leste" },
        { "c\u00f3digo": "TON", pais: "Tonga" },
        { "c\u00f3digo": "TTO", pais: "Trinidad y Tobago" },
        { "c\u00f3digo": "TUN", pais: "T\u00c3\u00banez" },
        { "c\u00f3digo": "TUR", pais: "Turqu\u00c3\u00ada" },
        { "c\u00f3digo": "TUV", pais: "Tuvalu" },
        {
          "c\u00f3digo": "TWN",
          pais: "Taiw\u00c3\u00a1n (Provincia de China)",
        },
        {
          "c\u00f3digo": "TZA",
          pais: "Tanzania, Rep\u00c3\u00bablica Unida de",
        },
        { "c\u00f3digo": "UGA", pais: "Uganda" },
        { "c\u00f3digo": "UKR", pais: "Ucrania" },
        {
          "c\u00f3digo": "UMI",
          pais: "Islas de Ultramar Menores de Estados Unidos (",
        },
        { "c\u00f3digo": "URY", pais: "Uruguay" },
        { "c\u00f3digo": "USA", pais: "Estados Unidos (los)" },
        { "c\u00f3digo": "UZB", pais: "Uzbekist\u00c3\u00a1n" },
        {
          "c\u00f3digo": "VAT",
          pais: "Santa Sede[Estado de la Ciudad del Vaticano] ",
        },
        { "c\u00f3digo": "VCT", pais: "San Vicente y las Granadinas" },
        { "c\u00f3digo": "VEN", pais: "Venezuela, Rep" },
        {
          "c\u00f3digo": "VGB",
          pais: "Islas V\u00c3\u00adrgenes (Brit\u00c3\u00a1nicas)",
        },
        {
          "c\u00f3digo": "VIR",
          pais: "Islas V\u00c3\u00adrgenes (EE.UU.)",
        },
        { "c\u00f3digo": "VNM", pais: "Viet Nam" },
        { "c\u00f3digo": "VUT", pais: "Vanuatu" },
        { "c\u00f3digo": "WLF", pais: "Wallis y Futuna" },
        { "c\u00f3digo": "WSM", pais: "Samoa" },
        { "c\u00f3digo": "YEM", pais: "Yemen" },
        { "c\u00f3digo": "ZAF", pais: "Sud\u00c3\u00a1frica" },
        { "c\u00f3digo": "ZMB", pais: "Zambia" },
        { "c\u00f3digo": "ZWE", pais: "Zimbabue" },
        { "c\u00f3digo": "ZZZ", pais: "Pa\u00c3\u00adses no declarados" },
      ],
    });
  } catch (error) {
    console.log(error);
    res.status(500).send({ error });
  }
};

module.exports = { getCountries };
