const getCountries = async (req, res, next) => {
  try {
    res.status(200).send({
      paises: [
        { código: "ABW", pais: "Aruba" },
        { código: "AFG", pais: "Afganistán" },
        { código: "AGO", pais: "Angola" },
        { código: "AIA", pais: "Anguila" },
        { código: "ALA", pais: "Islas Åland" },
        { código: "ALB", pais: "Albania" },
        { código: "AND", pais: "Andorra" },
        {
          código: "ARE",
          pais: "Emiratos Árabes Unidos (Los)",
        },
        { código: "ARG", pais: "Argentina" },
        { código: "ARM", pais: "Armenia" },
        { código: "ASM", pais: "Samoa Americana" },
        { código: "ATA", pais: "Antártida" },
        {
          código: "ATF",
          pais: "Territorios Australes Franceses (los)",
        },
        { código: "ATG", pais: "Antigua y Barbuda" },
        { código: "AUS", pais: "Australia" },
        { código: "AUT", pais: "Austria" },
        { código: "AZE", pais: "Azerbaiyán" },
        { código: "BDI", pais: "Burundi" },
        { código: "BEL", pais: "Bélgica" },
        { código: "BEN", pais: "Benín" },
        { código: "BES", pais: "Bonaire, San Eustaquio y Saba" },
        { código: "BFA", pais: "Burkina Faso" },
        { código: "BGD", pais: "Bangladés" },
        { código: "BGR", pais: "Bulgaria" },
        { código: "BHR", pais: "Baréin" },
        { código: "BHS", pais: "Bahamas (las)" },
        { código: "BIH", pais: "Bosnia y Herzegovina" },
        { código: "BLM", pais: "San Bartolomé" },
        { código: "BLR", pais: "Bielorrusia" },
        { código: "BLZ", pais: "Belice" },
        { código: "BMU", pais: "Bermudas" },
        { código: "BOL", pais: "Bolivia, Estado Plurinacional de" },
        { código: "BRA", pais: "Brasil" },
        { código: "BRB", pais: "Barbados" },
        { código: "BRN", pais: "Brunéi Darussalam" },
        { código: "BTN", pais: "Bután" },
        { código: "BVT", pais: "Isla Bouvet" },
        { código: "BWA", pais: "Botsuana" },
        {
          código: "CAF",
          pais: "República Centroafricana (la)",
        },
        { código: "CAN", pais: "Canadá" },
        { código: "CCK", pais: "Islas Cocos (Keeling)" },
        { código: "CHE", pais: "Suiza" },
        { código: "CHL", pais: "Chile" },
        { código: "CHN", pais: "China" },
        { código: "CIV", pais: "Côte d'Ivoire" },
        { código: "CMR", pais: "Camerún" },
        {
          código: "COD",
          pais: "Congo (la República Democrática del)",
        },
        { código: "COG", pais: "Congo" },
        { código: "COK", pais: "Islas Cook (las)" },
        { código: "COL", pais: "Colombia" },
        { código: "COM", pais: "Comoras" },
        { código: "CPV", pais: "Cabo Verde" },
        { código: "CRI", pais: "Costa Rica" },
        { código: "CUB", pais: "Cuba" },
        { código: "CUW", pais: "Curaçao" },
        { código: "CXR", pais: "Isla de Navidad" },
        { código: "CYM", pais: "Islas Caimán (las)" },
        { código: "CYP", pais: "Chipre" },
        { código: "CZE", pais: "República Checa (la)" },
        { código: "DEU", pais: "Alemania" },
        { código: "DJI", pais: "Yibuti" },
        { código: "DMA", pais: "Dominica" },
        { código: "DNK", pais: "Dinamarca" },
        {
          código: "DOM",
          pais: "República Dominicana (la)",
        },
        { código: "DZA", pais: "Argelia" },
        { código: "ECU", pais: "Ecuador" },
        { código: "EGY", pais: "Egipto" },
        { código: "ERI", pais: "Eritrea" },
        { código: "ESH", pais: "Sahara Occidental" },
        { código: "ESP", pais: "España" },
        { código: "EST", pais: "Estonia" },
        { código: "ETH", pais: "Etiopía" },
        { código: "FIN", pais: "Finlandia" },
        { código: "FJI", pais: "Fiyi" },
        { código: "FLK", pais: "Islas Malvinas [Falkland] (las)" },
        { código: "FRA", pais: "Francia" },
        { código: "FRO", pais: "Islas Feroe (las)" },
        {
          código: "FSM",
          pais: "Micronesia (los Estados Federados de)",
        },
        { código: "GAB", pais: "Gabón" },
        { código: "GBR", pais: "Reino Unido (el)" },
        { código: "GEO", pais: "Georgia" },
        { código: "GGY", pais: "Guernsey" },
        { código: "GHA", pais: "Ghana" },
        { código: "GIB", pais: "Gibraltar" },
        { código: "GIN", pais: "Guinea" },
        { código: "GLP", pais: "Guadalupe" },
        { código: "GMB", pais: "Gambia (La)" },
        { código: "GNB", pais: "Guinea-Bisáu" },
        { código: "GNQ", pais: "Guinea Ecuatorial" },
        { código: "GRC", pais: "Grecia" },
        { código: "GRD", pais: "Granada" },
        { código: "GRL", pais: "Groenlandia" },
        { código: "GTM", pais: "Guatemala" },
        { código: "GUF", pais: "Guayana Francesa" },
        { código: "GUM", pais: "Guam" },
        { código: "GUY", pais: "Guyana" },
        { código: "HKG", pais: "Hong Kong" },
        { código: "HMD", pais: "Isla Heard e Islas McDonald" },
        { código: "HND", pais: "Honduras" },
        { código: "HRV", pais: "Croacia" },
        { código: "HTI", pais: "Haití" },
        { código: "HUN", pais: "Hungría" },
        { código: "IDN", pais: "Indonesia" },
        { código: "IMN", pais: "Isla de Man" },
        { código: "IND", pais: "India" },
        {
          código: "IOT",
          pais: "Territorio Británico del Océano Índico (el)",
        },
        { código: "IRL", pais: "Irlanda" },
        {
          código: "IRN",
          pais: "Irán (la República Islámica de)",
        },
        { código: "IRQ", pais: "Irak" },
        { código: "ISL", pais: "Islandia" },
        { código: "ISR", pais: "Israel" },
        { código: "ITA", pais: "Italia" },
        { código: "JAM", pais: "Jamaica" },
        { código: "JEY", pais: "Jersey" },
        { código: "JOR", pais: "Jordania" },
        { código: "JPN", pais: "Japón" },
        { código: "KAZ", pais: "Kazajistán" },
        { código: "KEN", pais: "Kenia" },
        { código: "KGZ", pais: "Kirguistán" },
        { código: "KHM", pais: "Camboya" },
        { código: "KIR", pais: "Kiribati" },
        { código: "KNA", pais: "San Cristóbal y Nieves" },
        {
          código: "KOR",
          pais: "Corea (la República de)",
        },
        { código: "KWT", pais: "Kuwait" },
        {
          código: "LAO",
          pais: "Lao, (la) República Democrática Popular",
        },
        { código: "LBN", pais: "Líbano" },
        { código: "LBR", pais: "Liberia" },
        { código: "LBY", pais: "Libia" },
        { código: "LCA", pais: "Santa Lucía" },
        { código: "LIE", pais: "Liechtenstein" },
        { código: "LKA", pais: "Sri Lanka" },
        { código: "LSO", pais: "Lesoto" },
        { código: "LTU", pais: "Lituania" },
        { código: "LUX", pais: "Luxemburgo" },
        { código: "LVA", pais: "Letonia" },
        { código: "MAC", pais: "Macao" },
        {
          código: "MAF",
          pais: "San Martín (parte francesa)",
        },
        { código: "MAR", pais: "Marruecos" },
        { código: "MCO", pais: "Mónaco" },
        { código: "MDA", pais: "Moldavia (la Rep" },
        { código: "MDG", pais: "Madagascar" },
        { código: "MDV", pais: "Maldivas" },
        { código: "MEX", pais: "México" },
        { código: "MHL", pais: "Islas Marshall (las)" },
        {
          código: "MKD",
          pais: "Macedonia (la antigua República Yugoslava de)",
        },
        { código: "MLI", pais: "Malí" },
        { código: "MLT", pais: "Malta" },
        { código: "MMR", pais: "Myanmar" },
        { código: "MNE", pais: "Montenegro" },
        { código: "MNG", pais: "Mongolia" },
        { código: "MNP", pais: "Islas Marianas del Norte (las)" },
        { código: "MOZ", pais: "Mozambique" },
        { código: "MRT", pais: "Mauritania" },
        { código: "MSR", pais: "Montserrat" },
        { código: "MTQ", pais: "Martinica" },
        { código: "MUS", pais: "Mauricio" },
        { código: "MWI", pais: "Malaui" },
        { código: "MYS", pais: "Malasia" },
        { código: "MYT", pais: "Mayotte" },
        { código: "NAM", pais: "Namibia" },
        { código: "NCL", pais: "Nueva Caledonia" },
        { código: "NER", pais: "Níger (el)" },
        { código: "NFK", pais: "Isla Norfolk" },
        { código: "NGA", pais: "Nigeria" },
        { código: "NIC", pais: "Nicaragua" },
        { código: "NIU", pais: "Niue" },
        { código: "NLD", pais: "Países Bajos (los)" },
        { código: "NOR", pais: "Noruega" },
        { código: "NPL", pais: "Nepal" },
        { código: "NRU", pais: "Nauru" },
        { código: "NZL", pais: "Nueva Zelanda" },
        { código: "OMN", pais: "Omán" },
        { código: "PAK", pais: "Pakistán" },
        { código: "PAN", pais: "Panamá" },
        { código: "PCN", pais: "Pitcairn" },
        { código: "PER", pais: "Perú" },
        { código: "PHL", pais: "Filipinas (las)" },
        { código: "PLW", pais: "Palaos" },
        { código: "PNG", pais: "Papúa Nueva Guinea" },
        { código: "POL", pais: "Polonia" },
        { código: "PRI", pais: "Puerto Rico" },
        {
          código: "PRK",
          pais: "Corea (la República Democrática Popular de)",
        },
        { código: "PRT", pais: "Portugal" },
        { código: "PRY", pais: "Paraguay" },
        { código: "PSE", pais: "Palestina, Estado de" },
        { código: "PYF", pais: "Polinesia Francesa" },
        { código: "QAT", pais: "Catar" },
        { código: "REU", pais: "Reunión" },
        { código: "ROU", pais: "Rumania" },
        {
          código: "RUS",
          pais: "Rusia, (la) Federación de",
        },
        { código: "RWA", pais: "Ruanda" },
        { código: "SAU", pais: "Arabia Saudita" },
        { código: "SDN", pais: "Sudán (el)" },
        { código: "SEN", pais: "Senegal" },
        { código: "SGP", pais: "Singapur" },
        {
          código: "SGS",
          pais: "Georgia del sur y las islas sandwich del sur",
        },
        {
          código: "SHN",
          pais: "Santa Helena, Ascensión y Tristán de Acuña",
        },
        { código: "SJM", pais: "Svalbard y Jan Mayen" },
        { código: "SLB", pais: "Islas Salomón (las)" },
        { código: "SLE", pais: "Sierra leona" },
        { código: "SLV", pais: "El Salvador" },
        { código: "SMR", pais: "San Marino" },
        { código: "SOM", pais: "Somalia" },
        { código: "SPM", pais: "San Pedro y Miquelón" },
        { código: "SRB", pais: "Serbia" },
        { código: "SSD", pais: "Sudán del Sur" },
        {
          código: "STP",
          pais: "Santo Tomé y Príncipe",
        },
        { código: "SUR", pais: "Surinam" },
        { código: "SVK", pais: "Eslovaquia" },
        { código: "SVN", pais: "Eslovenia" },
        { código: "SWE", pais: "Suecia" },
        { código: "SWZ", pais: "Suazilandia" },
        { código: "SXM", pais: "Sint Maarten (parte holandesa)" },
        { código: "SYC", pais: "Seychelles" },
        {
          código: "SYR",
          pais: "Siria, (la) República Árabe",
        },
        { código: "TCA", pais: "Islas Turcas y Caicos (las)" },
        { código: "TCD", pais: "Chad" },
        { código: "TGO", pais: "Togo" },
        { código: "THA", pais: "Tailandia" },
        { código: "TJK", pais: "Tayikist" },
        { código: "TKL", pais: "Tokelau" },
        { código: "TKM", pais: "Turkmenistán" },
        { código: "TLS", pais: "Timor-Leste" },
        { código: "TON", pais: "Tonga" },
        { código: "TTO", pais: "Trinidad y Tobago" },
        { código: "TUN", pais: "Túnez" },
        { código: "TUR", pais: "Turquía" },
        { código: "TUV", pais: "Tuvalu" },
        {
          código: "TWN",
          pais: "Taiwán (Provincia de China)",
        },
        {
          código: "TZA",
          pais: "Tanzania, República Unida de",
        },
        { código: "UGA", pais: "Uganda" },
        { código: "UKR", pais: "Ucrania" },
        {
          código: "UMI",
          pais: "Islas de Ultramar Menores de Estados Unidos (",
        },
        { código: "URY", pais: "Uruguay" },
        { código: "USA", pais: "Estados Unidos (los)" },
        { código: "UZB", pais: "Uzbekistán" },
        {
          código: "VAT",
          pais: "Santa Sede[Estado de la Ciudad del Vaticano] ",
        },
        { código: "VCT", pais: "San Vicente y las Granadinas" },
        { código: "VEN", pais: "Venezuela, Rep" },
        {
          código: "VGB",
          pais: "Islas Vírgenes (Británicas)",
        },
        {
          código: "VIR",
          pais: "Islas Vírgenes (EE.UU.)",
        },
        { código: "VNM", pais: "Viet Nam" },
        { código: "VUT", pais: "Vanuatu" },
        { código: "WLF", pais: "Wallis y Futuna" },
        { código: "WSM", pais: "Samoa" },
        { código: "YEM", pais: "Yemen" },
        { código: "ZAF", pais: "Sudáfrica" },
        { código: "ZMB", pais: "Zambia" },
        { código: "ZWE", pais: "Zimbabue" },
        { código: "ZZZ", pais: "Países no declarados" },
      ],
    });
  } catch (error) {
    console.log(error);
    res.status(500).send({ error });
  }
};

module.exports = { getCountries };
